<a href="https://colab.research.google.com/github/sanapathisriram/NASSCOM_25211A66f4/blob/main/DAY2-numpy-exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import json

with open('/content/numpy.ipynb', 'r', encoding='utf-8') as f:
    notebook_data = json.load(f)

cells = notebook_data.get('cells', [])
code_cells = [c for c in cells if c.get('cell_type') == 'code']

for i, cell in enumerate(code_cells):
    print(f"--- Code Cell {i+1} ---")
    print(''.join(cell.get('source', [])))
    print('\n')

--- Code Cell 1 ---
import numpy as np


--- Code Cell 2 ---
# -----------------------------------------------------------
# 🔹 1. ARRAY CREATION FUNCTIONS
# -----------------------------------------------------------

# arange(): Create range of numbers like Python's range()
arr1 = np.arange(0, 10, 2)
print("Array using arange:", arr1)




--- Code Cell 3 ---
# linspace(): Create evenly spaced values between two limits
arr2 = np.linspace(0, 1, 5)
print("Array using linspace:", arr2)




--- Code Cell 4 ---
# reshape(): Change shape without changing data
arr3 = np.arange(1, 10).reshape((3, 3))
print("Reshaped Array (3x3):\n", arr3)

# flatten(): Convert multi-dimensional array to 1D
print("Flattened version:", arr3.flatten())


--- Code Cell 5 ---
# -----------------------------------------------------------
# 🔹 2. AGGREGATE FUNCTIONS
# -----------------------------------------------------------

data = np.array([[5, 8, 9], [2, 4, 6]])

print("Original Data:\n", data)



--- Code Cell 6

In [15]:
import json

with open('/content/NumPy_Exercise.ipynb', 'r', encoding='utf-8') as f:
    exercise_data = json.load(f)

cells = exercise_data.get('cells', [])
code_cells = [c for c in cells if c.get('cell_type') == 'code']

for i, cell in enumerate(code_cells):
    print(f"--- Code Cell {i+1} ---")
    print(''.join(cell.get('source', [])))
    print('\n')

--- Code Cell 1 ---
import numpy as np

print("--- Intermediate NumPy Exercise ---")
print("Complete each task by writing the requested NumPy code.")
print("-----------------------------------")

# Task 1: Array Creation Shortcuts
print("\n--- Task 1: Array Creation Shortcuts ---")
# 1.1 Create a 1D array named 'arr1_1' with numbers from 0 to 99 (inclusive) using arange.
# 1.2 Create a 3x3 array named 'arr1_2' filled with ones.
# 1.3 Create a 2x4 array named 'arr1_3' filled with the number 7.
# 1.4 Create a 5x5 array named 'arr1_4' with random integers between 10 and 50 (inclusive).

# Your code for Task 1 here:


print("arr1_1 (first 10 elements):", arr1_1[:10])
print("arr1_2:\n", arr1_2)
print("arr1_3:\n", arr1_3)
print("arr1_4 (first 2 rows):\n", arr1_4[:2])


# Task 2: Indexing and Slicing with Arrays
print("\n--- Task 2: Indexing and Slicing with Arrays ---")
data = np.array([[10, 20, 30, 40],
                 [50, 60, 70, 80],
                 [90, 100, 110, 120],
               

In [16]:
import numpy as np

In [17]:
print("--- Intermediate NumPy Exercise ---")
print("Complete each task by writing the requested NumPy code.")
print("-----------------------------------")

--- Intermediate NumPy Exercise ---
Complete each task by writing the requested NumPy code.
-----------------------------------


In [18]:
print("\n--- Task 1: Array Creation Shortcuts ---")


--- Task 1: Array Creation Shortcuts ---


In [19]:
print("\n--- Task 2: Indexing and Slicing with Arrays ---")
data = np.array([[10, 20, 30, 40],
                 [50, 60, 70, 80],
                 [90, 100, 110, 120],
                 [130, 140, 150, 160]])


--- Task 2: Indexing and Slicing with Arrays ---


In [20]:
print("\n--- Task 3: Conditional Operations ---")
arr3_1 = np.random.randint(1, 21, size=(4, 5))


--- Task 3: Conditional Operations ---


In [21]:
print("\n--- Task 4: Aggregation Functions ---")
arr4_1 = np.array([[10, 5, 12],
                   [3, 8, 15],
                   [20, 7, 4]])


--- Task 4: Aggregation Functions ---


In [22]:
print("\n--- Task 7: Copying vs. Viewing Arrays ---")
original_arr7 = np.array([1, 2, 3, 4, 5])


--- Task 7: Copying vs. Viewing Arrays ---


In [23]:
print("\n--- Task 8: Stacking and Splitting Arrays ---")
arr8_a = np.array([[1, 2], [3, 4]])
arr8_b = np.array([[5, 6], [7, 8]])
arr8_c = np.array([[9, 10]])


--- Task 8: Stacking and Splitting Arrays ---


In [24]:
print("\n--- Task 9: Sorting and Searching ---")
arr9_1 = np.array([5, 2, 8, 1, 9, 4, 7, 3, 6])
arr9_2d = np.array([[30, 20, 10],
                    [60, 50, 40],
                    [90, 80, 70]])


--- Task 9: Sorting and Searching ---


In [2]:
import numpy as np

In [3]:
arr1 = np.arange(0, 10, 2)
print("Array using arange:", arr1)

Array using arange: [0 2 4 6 8]


In [4]:
arr2 = np.linspace(0, 1, 5)
print("Array using linspace:", arr2)

Array using linspace: [0.   0.25 0.5  0.75 1.  ]


In [5]:
arr3 = np.arange(1, 10).reshape((3, 3))
print("Reshaped Array (3x3):\n", arr3)
print("Flattened version:", arr3.flatten())

Reshaped Array (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened version: [1 2 3 4 5 6 7 8 9]


In [6]:
data = np.array([[5, 8, 9], [2, 4, 6]])
print("Original Data:\n", data)

Original Data:
 [[5 8 9]
 [2 4 6]]


In [7]:
print("Sum of all elements:", np.sum(data))
print("Column-wise sum:", np.sum(data, axis=0))
print("Row-wise mean:", np.mean(data, axis=1))
print("Max value:", np.max(data))

Sum of all elements: 34
Column-wise sum: [ 7 12 15]
Row-wise mean: [7.33333333 4.        ]
Max value: 9


In [8]:
print("Index of max value (flattened):", np.argmax(data))
print("Min value:", np.min(data))
print("Standard Deviation:", np.std(data))

Index of max value (flattened): 2
Min value: 2
Standard Deviation: 2.3570226039551585


In [9]:
a = np.array([3, 1, 7, 2, 9])
print("Original Array:", a)

Original Array: [3 1 7 2 9]


In [10]:
sorted_array = np.sort(a)
print("Sorted Array:", sorted_array)
idx = np.where(a > 4)
print("Indices where value > 4:", idx)
print("Values > 4:", a[idx])

Sorted Array: [1 2 3 7 9]
Indices where value > 4: (array([2, 4]),)
Values > 4: [7 9]


In [11]:
arr = np.array([10, 20, 30, 40, 50, 60])
print("Original 1D Array:", arr)
print("Element at index 0:", arr[0])
print("Element at last index:", arr[-1])

Original 1D Array: [10 20 30 40 50 60]
Element at index 0: 10
Element at last index: 60


In [12]:
print("Slice from index 1 to 4:", arr[1:4])
print("Every second element:", arr[::2])
print("Reversed array:", arr[::-1])

Slice from index 1 to 4: [20 30 40]
Every second element: [10 30 50]
Reversed array: [60 50 40 30 20 10]


In [13]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Original Matrix:\n", matrix)
print("Element at (1,2):", matrix[1, 2])
print("First row:", matrix[0, :])
print("Second column:", matrix[:, 1])
print("Top-left 2x2 block:\n", matrix[:2, :2])

Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at (1,2): 6
First row: [1 2 3]
Second column: [2 5 8]
Top-left 2x2 block:
 [[1 2]
 [4 5]]


In [14]:
arr = np.array([5, 10, 15, 20, 25, 30])
mask = arr > 15
print("Boolean Mask:", mask)
print("Values greater than 15:", arr[mask])
print("Even numbers > 10:", arr[(arr > 10) & (arr % 2 == 0)])

Boolean Mask: [False False False  True  True  True]
Values greater than 15: [20 25 30]
Even numbers > 10: [20 30]
